# -*- coding: utf-8 -*-
"""numpy_scores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xaf3NP9D0mvk6HwNz2tnw5xn3-bwl6OA

Task 1: Generate and Inspect the Data
"""

import numpy as np

np.random.seed(42)
scores = np.random.randint(50, 101, size=(5, 4))

print("Full Scores Array:\n", scores)

print(f"\n3rd Student, 2nd Subject: {scores[2, 1]}")

print(f"\nLast 2 Students:\n{scores[-2:]}")

print(f"\nFirst 3 Students (Subj 2 & 3):\n{scores[:3, 1:3]}")

"""Task 2: Analyze with Broadcasting

"""

subject_means = np.mean(scores, axis=0).round(2)
print(f"Average score per subject: {subject_means}")

curve = np.array([5, 3, 7, 2])
curved_scores = np.clip(scores + curve, 0, 100)
print(f"\nCurved Scores:\n{curved_scores}")

best_per_student = np.max(curved_scores, axis=1)
print(f"\nBest score per student: {best_per_student}")

"""Task 3: Normalize and Identify"""

row_min = curved_scores.min(axis=1, keepdims=True)
row_max = curved_scores.max(axis=1, keepdims=True)

normalized_scores = (curved_scores - row_min) / (row_max - row_min)
print("Normalized Array:\n", normalized_scores.round(3))

max_idx_flat = np.argmax(normalized_scores)
row_idx, col_idx = np.unravel_index(max_idx_flat, normalized_scores.shape)
print(f"\nHighest value location: Student {row_idx}, Subject {col_idx}")

above_90 = curved_scores[curved_scores > 90]
print(f"\nScores strictly above 90: {above_90}")

